### PR TITLE
Better formatting of analysis page

### LINKED ISSUE #138: Only show warning about fake data in graph once, not for every column

### LINKED ISSUE #150: Better formatting of demo help on analysis page
Looking at #142: Need to integrate tooltips into labels.

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #150 
- Fix #138 
- Builds on #142: Merge that first.

### CODE REVIEW

**Review by ekraffmiller — COMMENTED** [review]
This looks good and the UI has the changes described.  I noticed that `output` and `session` aren't used in analysis_server(), can they be removed?

**Comment by pdurbin** [comment]
Please resolve the merge conflicts.

**Comment by mccalluc** [comment]
@ekraffmiller 
> I noticed that output and session aren't used in analysis_server(), can they be removed?

not really: These aren't functions I call, instead, it's an interface defined by Shiny that we need to satisfy. If I delete them in `dataset_panel` I get this error:
```
TypeError: dataset_server() got multiple values for argument 'csv_path'
```
I think since it's missing expected positional parameters, it's grabbing kwargs, and things get confused.

Will resolve conflicts and ask for re-review.

**Review by ekraffmiller — APPROVED** [review]
looks good, approved

**Pull request merged**
