### PR TITLE
Better handing for `--demo`

### LINKED ISSUE #75: More explanation in UI when running with `--demo`

### LINKED ISSUE #81: Handle `--demo` nicely on first tab
Either the name of the demo csv should show up in the upload widget, or we should just show the name of the demo csv in place of the widget. (Right now it is just empty.)

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #81: We can't actually set the value of the upload widget, but we can set placeholder text. 
- Fix #75: Add tool tips on the first tab if we're running with `--demo`

Does not address:
- #32

Eventually, we want the inputs on this screen to be frozen if they have been set from the CLI.

### CODE REVIEW

**Comment by ekraffmiller** [comment]
Looks good! UI Suggestion:  When running with --demo, don't show the FileUpload component, since demo.csv is being used.  Include some text about demo being used instead.

**Review by ekraffmiller — APPROVED** [review]
Approved with a follow up suggestion for UI

**Comment by mccalluc** [comment]
- Filed #113

**Comment by mccalluc** [comment]
App test fails:
```
        # -- Download results --
        page.get_by_role("button", name="Download results").click()
        expect_not_visible(pick_dataset_text)
>       expect_not_visible(perform_analysis_text)
```
Looking at the trace, it looks like it might have gotten bogged down in recalculating the graphs and didn't respond to the mouseclick to move to the next page quickly enough. Is there a risk of the application being unresponsive?

For now, just try to run run the tests.

**Comment by mccalluc** [comment]
- Filed #116

**Pull request merged**
